name: Rain Checker

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  check-rain:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit/push state file

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run rain monitor
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          PUSHBULLET_TOKEN: ${{ secrets.PUSHBULLET_TOKEN }}
        run: python main.py
