name: Rain Checker

on:
  schedule:
    - cron: "*/10 * * * *"  # runs every 10 minutes
  workflow_dispatch:       # allows manual trigger

jobs:
  check-rain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      env:
        OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
        PUSHBULLET_TOKEN: ${{ secrets.PUSHBULLET_TOKEN }}
      run: |
        python main.py
